# Generated by Django 2.0.7 on 2018-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='hero_image',
            field=models.ImageField(upload_to='webscrapper/model_images'),
        ),
    ]
