# Generated by Django 2.0.7 on 2018-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0004_auto_20180803_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
