# Generated by Django 2.0.7 on 2018-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0005_auto_20180803_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='picture',
            field=models.ImageField(default='static/author_picture.png', upload_to='webscrapper/imgs/author'),
        ),
    ]
